title: "Ceyhun Şen"

encoding: "utf-8"
markdown_ext: "md"
livereload: true
timezone: "Europe/Istanbul"

collections:
  blog:
    output: true
    permalink: /:collection/:title
  technical-writings:
    output: true
    permalink: /:collection/:title
  travel-logs:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "technical-writings"
    values:
      layout: "technical"
  - scope:
      path: ""
      type: "travel-logs"
    values:
      layout: "travel-logs"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - LICENSE
  - README.md

# For the sitemap generation
url: "https://ceyhunsen.me"
plugins:
  - jekyll-sitemap
