title: "Ceyhun Şen"

encoding: "utf-8"
markdown_ext: "md"
livereload: true
timezone: "Europe/Istanbul"

collections:
  blog:
    output: true
    permalink: /:collection/:title
  technical:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "technical"
    values:
      layout: "technical"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - LICENSE
  - README.md
