title: "Ceyhun Şen"

encoding: "utf-8"
markdown_ext: "md"
livereload: true
timezone: "Europe/Istanbul"

collections:
  experience:
    output: true
    sort_by: orderno
  projects:
    output: true
    sort_by: category
  competitions:
    output: true
    sort_by: orderno

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - LICENSE
  - README.md
